const jwt = require('jsonwebtoken');
const termtoken ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyZGF0YSI6eyJpZCI6NSwiTmFtZSI6ImJlbjEwIiwiTW9iaWxlIjo0NTc4NTI0MTc4LCJBZGRyZXNzIjoiYmVuIHZpbGxhIiwiQ2l0eSI6ImJlbnRlbiIsIlN0YXRlIjoiZW5nbGFuZCIsIlF1YWxpZmljYXRpb24iOiJQbHVzIHR3byIsIlNlcnZpY2UiOiJjYXJwZW50aW5nIiwiRXhwZXJpZW5jZSI6IjUgeXJzIiwiRW1haWwiOiJiZW5AZ21haWwuY29tIiwiUGFzc3dvcmQiOiJiZW4xMjM0NSIsIlJvbGUiOiJWZW5kb3IifSwiaWF0IjoxNjgwODU2NDMwLCJleHAiOjE2ODA4NjAwMzB9.YJGKCfrbIkprMV0NPvb83D4UD-bbdmcm7HEByzAAOnY"
const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6I…5Njd9.MIvl-7tmmPJRMOCKkxKTFGlMNV8KBm0xMk66K-GrCvY"

console.log(termtoken === token)